### ISSUE TITLE
Needs on object previews are unsigned, giving incorrect values

### ISSUE THREAD

**Issue by BakaOsaka** [riperiperi/Simitone#18]
Certain objects in The Sims have non-positive needs values which are not correctly represented in object previews.
The Espresso machine for example gives negative points to Bladder, but on the object preview it shows an incorrect value:
![Needs](https://i.imgur.com/V9VBAkM.jpg)

**Comment by riperiperi** [comment]
Simple one - that should be signed instead of unsigned.
