### ISSUE TITLE
Android build?

### ISSUE THREAD

**Issue by strikersix23** [riperiperi/Simitone#31]
I would like to build for android personal use I don't care about distribution. As I have no need for it

**Comment by MrPowerGamerBR** [comment]
A Android build (or any other OS really) can't be made because EA doesn't allow it: http://freeso.org/ts1-ios-port-cancelled/

So unless you are able to change the source code to make it buildable for other target OSes, making a Android port is impossible.

**Comment by strikersix23** [comment]
ok what about targeting. https://github.com/termux/termux-app
Itself is a linux enviroment but there are some limitions like no mono as its hard to use for general phones 

https://wiki.termux.com/wiki/Working_with_APKs

This will also allow you to target chrome books as well

**Comment by MrPowerGamerBR** [comment]
I'm pretty sure that EA disallowed any development for any other OS except Windows

**Comment by strikersix23** [comment]
Vala or valgrind is on termux but it will take some time to even setup gfx and be a pain to get c# working vala seems to be good option with little work

**Comment by EternalBlueFlame** [comment]
Theoretically, the program could have support for WSL, which would give indirect support for terminal based clients like termux, while still officially targeting a windows platform.

Alternatively, attacking it from the other end, Wine does have android builds, some support could be given to that, so it could run the project, this might be an easier approach and it fully steps around any legalities while also potentially helping the project support other windows applications.

**Comment by kzar** [comment]
This is a legal issue, not a technical one. By discussing technical workarounds here you could be jeopardising the project, by drawing attention from EA's legal team. If you want to play with getting the project to build for other platforms privately fair enough, but I think you should avoid public discussions about it like this out of respect for @riperiperi - it would really suck to cause him/her more legal difficulties.

**Comment by EternalBlueFlame** [comment]
Fair point. We know how EA can be. I deleted my comment.
Although with how they are handling sims, what with the latest expansion by 4 being hated by nearly the entire userbase, who collectively voted against it being made while it was in early development, maybe paralives will kill it, due the negligence and sheer ignorance to the community that's harbored by the souless suits running the branch. Just like sim city.
Then legalities shouldn't be an issue anymore.

**Comment by strikersix23** [comment]
Ok  I agree ill respect him and end this conversation i respect developers and i agrea ea is not using maxis software right, Communitys have been neglected in favor of profit by them
