### ISSUE TITLE
simitone is not working. what should i do?

### ISSUE THREAD

**Issue by sims2420** [riperiperi/Simitone#6]
OS : Window 7 (64bit)
Base : The Sims Complete Collection.

I got bulid/buy version of simitone. but it still crashes. crash are the same as the crash that besweeet sayed last time. I brought his photo that captured crash> https://i.imgur.com/Han71nM.png
since build/buy version say that don't need FreeSO, I don't have FreeSO.

I played sim, put on magic item to inventory and save game. also I don't use custom content. 
why simitone is crashing? please help me.

Original source of carsh photo : https://github.com/riperiperi/Simitone/issues/3

**Comment by id0nthaveause** [comment]
the same thing is happening to me except I never even got one chance to play it. Meaning it just won't start for whatever reason. Try reinstalling it?
