### ISSUE TITLE
Fatal Error?

### ISSUE THREAD

**Issue by id0nthaveause** [riperiperi/Simitone#9]
![fatal error](https://user-images.githubusercontent.com/47272815/53020454-e6f82580-3424-11e9-9b57-dfef067c17a3.PNG)
I was just going to try the new Simitone with save features but this happened. It's saying it can't find this file from Maxis? Is the .zip file missing it?

**Comment by riperiperi** [comment]
The Sims Complete Collection must be installed for Simitone to work (it needs to access the game files, objects etc). Additionally, I wouldn't recommend trying Simitone in its current stage, as there are still many issues that prevent it from being playable.

**Comment by id0nthaveause** [comment]
How do I get the complete collection? Do I need to install FreeSO?

**Comment by id0nthaveause** [comment]
I've also tried other versions, they don't work for me either... I might as well check ebay for the actual sims 1 disc

**Comment by riperiperi** [comment]
The Sims Complete Collection is a commercial collection of The Sims + all expansions. See: https://www.amazon.co.uk/Sims-Complete-Collection-PC-CD/dp/B0007YZUYA

**Comment by id0nthaveause** [comment]
ok

**Comment by id0nthaveause** [comment]
So that basically means that I could just play the actual sims 1 game for the same price as getting a collection for Simitone? Thanks for the info but I'm all set

**Comment by id0nthaveause** [comment]
Bc there is literally a new sims 1 disc for like 12 dollars no joke

**Comment by riperiperi** [comment]
Simitone is a replacement engine for The Sims. It is not a standalone game.

**Comment by id0nthaveause** [comment]
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooh ok nvm i'll get ts1 some time but for now i'll just play FreeSO thx

**Comment by id0nthaveause** [comment]
Wait i have one more thing. Now FreeSO is giving me a fatal error! 
![capture](https://user-images.githubusercontent.com/47272815/53037749-030dbe00-3449-11e9-892f-20f56399587e.PNG)

**Comment by id0nthaveause** [comment]
oh nvm i got it
this error is now closed

**Comment by KasaBerlin** [comment]
> oh nvm i got it
> this error is now closed

I have the same error. How did you solve it?
